version: '3.8'

services:
  observatoire_frontend:
    build:
      context: ./observatoire_frontend
      dockerfile: Dockerfile
      target: development
    container_name: frontend_container
    ports:
      - '3000:3000'

  observatoire_backend:
    build:
      context: ./observatoire_backend
      dockerfile: Dockerfile
      target: development
    container_name: backend_container
    ports:
      - '4000:4000'
    volumes:
      - ./observatoire_backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - mysql

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: observatoire_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    container_name: mysql_container
    ports:
      - '3306:3306'
